version: '3.4'
# docker-compose -f docker-compose.yml -f docker-compose.override.yml up --build
# docker-compose up -d
# Cardboard
# http://localhost:8000/swagger/index.html
# BasketCards
# http://localhost:8001/swagger/index.html
# Discount
# http://localhost:8002/swagger/index.html
# Catalog
# http://localhost:8004/swagger/index.html
# BasketProducts
# http://localhost:8005/swagger/index.html

services:
  cardboarddb:
    image: mongo
  
  basketcardsdb:
    image: redis

  discountdb: 
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  catalogdb:
    image: mongo

  basketproductsdb:
    image: mongo

  cardboard.api:
    image: ${DOCKER_REGISTRY-}cardboardapi
    build:
      context: .
      dockerfile: Services\CardBoard\CardBoard.API\Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services\Discount\Discount.API\Dockerfile

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateways\OcelotAPIGateway\Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services\Catalog\Catalog.API\Dockerfile

  basketproducts.api:
    image: ${DOCKER_REGISTRY-}basketproductsapi
    build:
      context: .
      dockerfile: Services\BasketProducts\BasketProducts.API\Dockerfile

  basketcards.api:
    image: ${DOCKER_REGISTRY-}basketcardsapi
    build:
      context: .
      dockerfile: Services\BasketCards\Basket.API\Dockerfile

volumes:
 mongo_data:
 portainer_data:
 postgres_data:
 pgadmin_data:
