version: '3.4'

services:
  cardboarddb:
    container_name: cardboarddb
    restart: always
    volumes:
        - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
        - "27017:27017"
  
  catalogdb:
    container_name: catalogdb
    restart: always
    volumes:
        - ${WEBAPP_STORAGE_HOME}/site_catalogdb:/data/db
    ports:
        - "27018:27017"
  
  basketcardsdb:
    container_name: basketcardsdb
    restart: always    
    ports:
        - "6379:6379"
  
  basketproductsdb:
    container_name: basketproductsdb
    restart: always
    ports:
        - "27019:27017"
    volumes:
        - mongo_data:/data/db

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  basketcards.api:
    container_name: basketcardsapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      #- "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - basketcardsdb
    ports:
      - "8001:80"

  cardboard.api:
    container_name: cardboardapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://cardboarddb:27017"
    depends_on:
      - cardboarddb
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8000:80"

  discount.api:
    container_name: discountapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      #- "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - discountdb
    ports:
      - "8002:80"

  ocelotapigateway:
    container_name: ocelotapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
        - cardboard.api
        - basketcards.api
        - discount.api
    #    - ordering.api
    ports:
      - "8010:80"

  catalog.api:
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27018"
     # - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    depends_on:
      - catalogdb
    ports:
      - "8004:80"

  basketproducts.api:
    container_name: basketproductsapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://basketproductsdb:27019"
     # - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    depends_on:
        - basketproductsdb
    ports:
        - "8005:80"

